language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - npm i f

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - npm run build
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend kariman/udagram-frontend:v1

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kariman/udagram-frontend:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kariman/udagram-frontend:v2
